config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'users#show'

  resources :contacts

  resources :emails

  resources :tasks do
    member do
      put :toggle_completed
    end
  end

  resources :users, only: [:edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  has_one_attached :photo
  # include PgSearch::Model
  #   multisearchable against: [ :first_name, :last_name, :company ]

  include PgSearch::Model
    pg_search_scope :search_by_contact,
      against: [ :first_name, :last_name, :company ],
      using: {
        tsearch: { prefix: true }
      }

  has_many :tasks, dependent: :destroy
  has_many :emails, dependent: :destroy

  belongs_to :user

  def full_name
    return  self.first_name + " " + self.last_name
  end

end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :contact

  include PgSearch::Model
  multisearchable against: [ :subject, :content ]

end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :contact, optional: true
  belongs_to :user

  include PgSearch::Model
  multisearchable against: [ :description ]

  CATEGORY = ["email", "appointment", "finance", "review" ]
  PRIORITY = ["Super Important", "High", "Medium", "Low" ]

  validates :category, inclusion: {in: CATEGORY}, allow_nil: true

  validates :priority, inclusion: {in: PRIORITY}, allow_nil: true

  #validates :contact_id, allow_nill: true

  def self.categories
    return CATEGORY
  end

  def self.priorities
    return PRIORITY
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :tasks, dependent: :destroy
  has_many :contacts, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username])
  end

def after_sign_in_path_for(resource)
  stored_location_for(resource) || dashboard_path
end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def index
    if params[:query].present?
      @contacts = Contact.search_by_contact(params[:query])
    else
      #@contacts = Contact.all
      @contacts = Contact.where(user: current_user)
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user = current_user
    if @contact.save!
      redirect_to contact_path(@contact), notice: "New Item Saved"
    else
      render :new
    end
  end

  def new
    @contact = Contact.new
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update_attributes(contact_params)
        redirect_to contacts_path, notice: "Contact Edited"
    else
        render :edit
    end
  end

  def destroy
    @contact = Contact.find(params[:id])
    if @contact.present?
      @contact.destroy
    end
    redirect_to contacts_path, notice: "Contact Deleted"
  end


  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :email, :instagram, :twitter, :linkedin, :photo)
  end
end

app/controllers/emails_controller.rb
class EmailsController < ApplicationController
    def index
        if params[:query].present?
      @emails = Email.search_by_email(params[:query])
    else
      #@emails = Email.all
      @emails = Email.joins(:contact).where(contacts: {user: current_user})
    end
  end

    def show
        @email = Email.find(params[:id])
    end

    def new
        @email = Email.new
    end

    def create
        @email = Email.new(email_params)
       # if @email.save
       #     redirect_to
       # else
       #     render :new
       # end
    end

    def edit
        @email = Email.find(params[:id])
    end

    def update
        @email = Email.find(params[:id])
    end

    private
    def email_params
        params.require(:email).permit(:to, :content, :cc, :date_time)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
 
  skip_before_action :authenticate_user!, only: :home

  def home
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    # before_action :set_task, only: [:show, :destroy]

    def index
        #@tasks = Task.all
        @tasks = Task.where(user: current_user)
    end

    def show
        @task = Task.find(params[:id])
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.new(task_params)
        @task.user = current_user
        @task.complete = false
        if @task.save!
            redirect_to task_path(@task), notice: "New Task Saved"
        else
            render :new
        end
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])

# byebug

        if @task.update_attributes!(task_params)
            redirect_to tasks_path(@task), notice: "Task Edited"
        else
            render :edit
        end
    end

    def toggle_completed
        @task = Task.find(params[:id])
# byebug
        @task.complete = !@task.complete

        if @task.save!
            redirect_to dashboard_path
        end
    end

    private
    def task_params
        params.require(:task).permit(:description, :contact_id, :priority, :date_time, :ownership, :complete, :category)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @tasks = Task.where(user: current_user)
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="contacts labels">
    <div class="form-inputs">
      <div class="d-flex justify-content-between mb-5">
        <span class="input-name"> <%= f.input :first_name, placeholder: "" %> </span>
        <span class="input-name"> <%= f.input :last_name, placeholder: "" %> </span>

      </div>
      <div>
        <%= f.input :email, placeholder: "name@gmail.com" %>
      </div>
      <div class="d-flex justify-content-between">
        <%= f.input :instagram %>
        <%= f.input :twitter %>
        <%= f.input :linkedin %>
      </div>
      <div class="d-flex justify-content-between">
        <%= f.input :photo, as: :file %>
          <input type="submit" name="commit" value="Save" class="logbtn" data-disable-with="Create Contact">

        <%= link_to contacts_path do %>
          <span class="logbtn">Back</span>
        <%end%>

      </div>

    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar col-2 col-sm-1">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="container mt-3">
      <div class="row justify-content-center">
        <div class="col-12" %>
          <h2 class="contact-header"><%= @contact.first_name %> <%= @contact.last_name %></h2>
          <%= render 'form', contact: @contact %>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/contacts/index.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="col-10">
      <div class="row inner-navbar">
        <%= render 'shared/navbar' %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-12">
            <span class="secbtn"><%= link_to "New Contact", new_contact_path %></span>
            <span class="secbtn"><%= link_to "Back", dashboard_path %></span>
            <div class="row">
              <% @contacts.each do |contact| %>
                <div class="col-12 p-2">
                  <div class="card-task">
                    <div class="card-body">
                      <h2 class="card-title"><%= contact.first_name %> <%= contact.last_name %></h2>

                      <p class="card-text"><%= contact.email %></p>
                      <p class="card-text"><%= contact.instagram %></p>
                      <p class="card-text"><%= contact.twitter %></p>
                      <p class="card-text"><%= contact.linkedin %></p>

                      <%= link_to "Show Contact", contact_path(contact) %>
                      <%= link_to "Edit Contact", edit_contact_path(contact) %>
                      <%= link_to "Delete", contact_path(contact), method: :delete, remote: true, data: { confirm: 'Are you sure?' }%>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar col-2 col-sm-1">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="container mt-3">
      <div class="row justify-content-center">
        <div class="col-12" %>
          <h2 class="contact-header">New Contact</h2>
          <%= render 'form', contact: @contact %>
        </div>
      </div>
    </div>
    
  </div>
</div>

app/views/contacts/show.html.erb
<div class="contact-container">
  <div class="row">
    <div class="sidebar col-2 col-sm-1">
      <%= render 'shared/sidebar' %>
    </div>

    <div id="navbar-color" class="col-10 col-sm-11 container p-5">
      <div class="row inner-navbar">
          <%= render 'shared/navbar' %>
      </div>

      <div id="container-height" class="row">
        <div id="contact-profile" class="col-4 justify-content-end">
              <h1 id="header"><strong>Guest Profile </strong></h1>
              <div class="col-12 card-body">
                      <div class="photo-profile d-flex">
                        <%if @contact.photo.present?%>
                          <img><%=cl_image_tag @contact.photo.key, height: 200, width: 200, crop: :fill %>
                        <%end%>
                        <h5 id="title" class="card-title"><%= @contact.first_name %> <%= @contact.last_name %></h5>
                      </div>
                      <div class="send-email d-flex">
                        <h2 class="card-text"><strong>Email</strong></h2>
                        <%= link_to dashboard_path do %>
                          <p class="card-button">Send Email</p>
                        <%end%>
                      </div>
                      <p id="cardtext" class="card-text"><%= @contact.email %></p>

                      <h2 id="cardtext" class="card-text"><strong>Instagram</strong></h2>
                      <p id="cardtext" class="card-text"><%= @contact.instagram %></p>

                      <h2 id="cardtext" class="card-text"><strong>Twitter</strong></h2>
                      <p id="cardtext" class="card-text"><%= @contact.twitter %></p>

                      <h2 id="cardtext" class="card-text"><strong>Linkedin</strong></h2>
                      <p id="cardtext" class="card-text"><%= @contact.linkedin %></p>
              </div>
        </div>

        <div class="col-8">
          <div class="contact-tasks">
            <div id="header" class="d-flex">
              <h2 class="special-header"><u>Timeline</u></h2>
              <h2 class="special-header">Notes</h2>
              <h2 class="special-header">Events</h2>
            </div>
            <div class="row">
              <div class="info d-flex">
                <div>
                  <h3 id="cardtext"> Podcast Uploaded: Epsiode #28 </h3>
                  <p id="cardtext"> Sarah Jones, Founder @ Healthy Nutrition </p>
                </div>
                <div>
                  <h3 id="cardtext"> 27/02/2021 </h3>
                  <p id="cardtext"> 2:03pm </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="info d-flex">
                <div>
                  <h3 id="cardtext"> Podcast Uploaded: Epsiode #28 </h3>
                  <p id="cardtext"> Sarah Jones, Founder @ Healthy Nutrition </p>
                </div>
                <div>
                  <h3 id="cardtext"> 1/03/2021 </h3>
                  <p id="cardtext"> 2:03pm </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="info d-flex">
                <div>
                  <h3 id="cardtext"> Podcast Uploaded: Epsiode #28 </h3>
                  <p id="cardtext"> Sarah Jones, Founder @ Healthy Nutrition </p>
                </div>
                <div>
                  <h3 id="cardtext"> 2/03/2021 </h3>
                  <p id="cardtext"> 2:03pm </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="info d-flex">
                <div>
                  <h3 id="cardtext"> Podcast Uploaded: Epsiode #28 </h3>
                  <p id="cardtext"> Sarah Jones, Founder @ Healthy Nutrition </p>
                </div>
                <div>
                  <h3 id="cardtext"> 28/03/2021 </h3>
                  <p id="cardtext"> 2:03pm </p>
                </div>
              </div>
            </div>

            <div class="row">
              <div class="info d-flex">
                <div>
                  <h3 id="cardtext"> Podcast Uploaded: Epsiode #28 </h3>
                  <p id="cardtext"> Sarah Jones, Founder @ Healthy Nutrition </p>
                </div>
                <div>
                  <h3 id="cardtext"> 27/03/2021 </h3>
                  <p id="cardtext"> 2:03pm </p>
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podforce</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>


    <link rel="shortcut icon" href="/assets/logo.jpg" type="image/x-icon">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Odibee+Sans&display=swap" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <%= favicon_link_tag asset_path("log-square2.png") %>

  </head>

  <body>

    <%= yield %>

    <%= render 'shared/flashes' %>

  </body>

</html>

app/views/pages/home.html.erb
<div class="main-container">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <div class="landing-podforce">
      <%= image_tag "log-logo.png" %>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>


          <li class="nav-item dropdown">
            <%= image_tag "headshot.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to "Contacts", contacts_path, class: "dropdown-item" %>
              <%= link_to "Tasks", tasks_path, class: "dropdown-item" %>
              <%= link_to "Emails", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>

        <% else %>

                <ul class="nav justify-content-end">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Features</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Product</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">Pricing</a>
                  </li>

                  <li class="nav-item secbtn">
                      <%= link_to "Signup", new_user_registration_path %>
                  </li>

                  <li class="nav-item secbtn">
                      <%= link_to "Login", new_user_session_path %>
                  </li>
                </ul>
        <% end %>
      </ul>
    </div>
  </div>



  <div class="hero-image">
    <div class="hero-text">
      <h2>Manage & Grow Your Podcast With Podforce!</h2>
      <p>All in one central platform</p>
      <span class="secbtn"><%= link_to "Try Now", new_user_registration_path %></span>
    </div>
  </div>


  <div class="container">
    <p></p>
    <h2 class="text-center login-header">How It Works</h2>
    <p></p>
    <div class="cards">

      <div class="card">
        <img src="f2.svg" alt="">
        <%= image_tag "contacts.svg" %>
        <h4>Manage Guests</h4>
        <p>Create contacts, schedule episodes, send emails.</p>
      </div>

      <div class="card">
        <img src="images/f2.svg" alt="">
        <%= image_tag "money.svg" %>
        <h4>Manage Sponsors</h4>
        <p>Share growth metrics</p>
      </div>

      <div class="card">
        <img src="images/product.svg" alt="">
        <%= image_tag "f2.svg" %>
        <h4>Grow Your Podcast</h4>
        <p>Create tasks & get shi*t done!</p>
      </div>

    </div>
  </div>


  <div class="footer">
    <div class ="text-center">
      <div class="links">
        <a href="#"><i class="fab fa-fw fa-facebook-f"></i></a>
        <a href="#"><i class="fab fa-fw fa-github"></i></a>
        <a href="#"><i class="fab fa-fw fa-twitter"></i></a>
        <a href="#"><i class="fab fa-fw fa-instagram"></i></a>
        <p class ="text-center">This website was coded with <i class="fas fa-heart"></i> by team Podforce.</p>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">

    <%= form_tag contacts_path, method: :get, class: "form-inline" do %>
      <%= search_field_tag :query,
        params[:query],
        placeholder: "Search for a Contact",
        class: "form-control navbar-search"
      %>

      <button type="submit" class="navbar-search"><i class="fas fa-search-location"></i>
      </button>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active secbtn">
          <%= link_to "Dashboard", dashboard_path%>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "headshot.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Contacts", contacts_path, class: "dropdown-item" %>
            <%= link_to "Tasks", tasks_path, class: "dropdown-item" %>
            <%= link_to "Emails", emails_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>

        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="col-10">
      <div class="row inner-navbar">
        <%= render 'shared/navbar' %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-12" %>
            <span class="secbtn"><%= link_to "New Task", new_task_path %></span>
            <span class="secbtn"><%= link_to "Back", dashboard_path %></span>
            <div class="row">
              <% @tasks.each do |task| %>
                <div class="col-12 p-2">
                  <div class="card-task">
                    <div class="card-body">
                      <h2 class="card-title"><%= task.description %></h2>
                      <p class="card-text"> <strong>Priority: </strong><%= task.priority %></p>
                      <p class="card-text"> <strong>Date: </strong><%= task.date_time %></p>
                      <div class="d-flex justify-content-center">
                        <p class="card-text"><strong>Complete: </strong>
                          <%= button_to toggle_completed_task_path(task), method: :put, remote: true, class: "checkbutton" do %>
                            <i class="far <%= task.complete ? "fa-check-square" : "fa-square" %>"></i>
                              <%#= f.input_field :complete, as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false %>
                              <%#= f.submit %>
                          <% end %>
                        </p>
                      </div>
                        

                      <p class="card-text"> <strong>Category: </strong><%= task.category %></p>
                      <%= link_to "Show Task", task_path(task) %>
                      <%= link_to "Edit Task", edit_task_path(task) %>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="col-10">
      <div class="row inner-navbar">
        <%= render 'shared/navbar' %>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-12">
            <span class="secbtn"><%= link_to "New Task", new_task_path %></span>
            <span class="secbtn"><%= link_to "Back", tasks_path %></span>
            <div class="row">
              <div class="col-12 p-2">
                <div class="card-task">
                  <div class="card-body">
                    <h2><%= @task.description %></h2>
                    <p class="card-text"> <strong>Priority: </strong><%= @task.priority %></p>
                    <p class="card-text"> <strong>Date: </strong><%= @task.date_time %></p>
                    <div class="d-flex justify-content-center">
                      <p class="card-text"> <strong>Complete:  </strong>
                    
                        <%= button_to toggle_completed_task_path(@task), method: :put, remote: true, class: "checkbutton" do %>
                          <i class="far <%= @task.complete ? "fa-check-square" : "fa-square" %>"></i>
                            <%#= f.input_field :complete, as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false %>
                            <%#= f.submit %>
                        <% end %>

                      </p>
                    </div>
                    

                    <p class="card-text"> <strong>Category: </strong><%= @task.category %></p>

                    <% if @task.category == "email" && @task.contact.present? %>
                      <div>
                        <a class= "secbtn" href="mailto: <%= @task.contact.email %> ?subject=Episode Live" style="">Send Email</a>
                      </div>
                    <%end%>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="dashboard-container">
  <div class="row">
    <div class="sidebar">
      <%= render 'shared/sidebar' %>
    </div>

    <div class="col-10 p-2 container">
      <div class="row inner-navbar">
          <%= render 'shared/navbar' %>
      </div>

      <div id="container-height" class="row">
        <div class="col-4">
          <div class="dashboard-reviews justify-content-end">
            <h1 id="header"><strong>Recent Review </strong></h1>
            <div class="col-12 ">
              <div>
                <div class="card-body d-flex">
                  <p class="card-title"> <strong> Comment </strong></p>
                  <p class="card-text"> Rating</p>
                </div>
              </div>
              <div id="reviews" class="card">
                <div class="card-body d-flex justify-content-evenly">
                  <p class="card-title"> Amazing podcast!</p>
                  <%= image_tag "five-stars.png"%>
                </div>
              </div>
              <div id="reviews" class="card">
                <div class="card-body d-flex justify-content-evenly">
                  <p class="card-title"> Loved the last Podcast!!</p>
                  <%= image_tag "4-starts.png"%>
                </div>
              </div>
              <div id="reviews" class="card">
                <div class="card-body d-flex justify-content-evenly">
                  <p class="card-title"> Great Content</p>
                  <%= image_tag "five-stars.png"%>
                </div>
              </div>

            </div>
          </div>
          <div class="dashboard-podcasts justify-content-end">
            <h1 id="special-heather">The LiveUltra Podcast</h1>



            <script type="text/javascript">
              <!--
              rssfeed_url = new Array();
              rssfeed_url[0]="https://theliveultrapodcast.libsyn.com/rss";
              rssfeed_frame_width="413";
              rssfeed_frame_height="458";
              rssfeed_scroll="off";
              rssfeed_scroll_step="6";
              rssfeed_scroll_bar="on";
              rssfeed_target="_blank";
              rssfeed_font_size="12";
              rssfeed_font_face="obidee-sans";
              rssfeed_border="on";
              rssfeed_css_url="https://feed.surfing-waves.com/css/style6.css";
              rssfeed_title="on";
              rssfeed_title_name="";
              rssfeed_title_bgcolor="#3366ff";
              rssfeed_title_color="#fff";
              rssfeed_title_bgimage="";
              rssfeed_footer="off";
              rssfeed_footer_name="rss feed";
              rssfeed_footer_bgcolor="#fff";
              rssfeed_footer_color="#333";
              rssfeed_footer_bgimage="";
              rssfeed_item_title_length="50";
              rssfeed_item_title_color="#666";
              rssfeed_item_bgcolor="#fff";
              rssfeed_item_bgimage="";
              rssfeed_item_border_bottom="on";
              rssfeed_item_source_icon="off";
              rssfeed_item_date="off";
              rssfeed_item_description="on";
              rssfeed_item_description_length="120";
              rssfeed_item_description_color="#666";
              rssfeed_item_description_link_color="#333";
              rssfeed_item_description_tag="off";
              rssfeed_no_items="0";
              rssfeed_cache = "875df16ee41da9abcd4c2e969f4db568";

            </script>
            <script type="text/javascript" src="//feed.surfing-waves.com/js/rss-feed.js"></script>
          </div>
        </div>

        <div class="col-8">
          <div class="dashboard-tasks">
            <h1 id="header"><strong>My Tasks</strong></h1>
            <div class="row">
              <% @tasks.each do |task| %>
                <div class="col-12 mt-3">
                  <div class="card-mini-task">
                    <div class="card-body d-flex justify-content-between">
                      <div class="p-3">
                        <%= button_to toggle_completed_task_path(task), method: :put, remote: true, class: "checkbutton" do %>
                          <i class="far <%= task.complete ? "fa-check-square" : "fa-square" %>"></i>
                            <%#= f.input_field :complete, as: :boolean, boolean_style: :inline, checked_value: true, unchecked_value: false %>
                            <%#= f.submit %>
                        <% end %>
                      </div>

                      <div class="d-flex justify-content-around p-3">
                        <%= link_to(task) do %>
                          <% if task.complete %>
                            <del id="card-title-design-underline" class="card-title"><%= task.description %></del>
                          <% else %>
                            <p id="card-title-design" class="card-title"><%= task.description %></p>
                          <% end %>
                        <% end %>
                      </div>


                      <div class="p-3">
                        <% if task.contact.present? %>
                          <% if task.contact.photo.present? %>
                            <%= cl_image_tag task.contact.photo.key, class:"picture"%>
                          <% end %>
                        <% end %>
                      </div>

                      <div class="ml-auto p-3">
                        <% if task.complete %>
                          <p id="card-title-design-underline" class="card-text"> <%= task.date_time %></p>
                        <% else %>
                          <p  class="card-text"> <%= task.date_time %></p>
                        <% end %>
                      </div>

                    </div>
                  </div>
                </div>
              <% end %>
              <div id="button" class="d-flex justify-content-center">
                <%= link_to "+", new_task_path, class: "btn secbtn" %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>